name: 'TOML Reader'
description: 'Read a specific field from a TOML file'
inputs:
  file:
    description: 'The TOML file to read from'
    required: true
  field:
    description: 'The field inside the TOML file to read'
    required: true
outputs:
  value:
    description: 'The data stored in `field` inside `file`'
runs:
  using: 'node12'
  main: 'index.js'

